### PR TITLE
Ownershiphandler

### PR DESCRIPTION
**Pull request by nomisum**
Adds a function to
* move new spawned units from zeus client to server to reduce performance impact through slow zeus machines
* apply loadout again if uniform is missing on server arrival
* apply loadout again if uniform is missing on HC arrival

**needs testing**

### CODE REVIEW

**Comment by nomisum** [comment]
limitations:
* doesnt work with zeus clients created on the fly

**Comment by nomisum** [comment]
We might be ninjaed by ACEX 

https://github.com/acemod/ACEX/pull/163/files

**Comment by McDiod** [comment]
I removed the automatic transfer to server, because AI would dismount vehicles. This now has:

* local EH, which reapplies loadout
* curator placed EHs which apply loadouts (different from before, where the CAManBase initEH would trigger for curator placed, but also on mission start, leading to double loadouts)

**Comment by McDiod** [comment]
Loadout is not applied when spawning units directly into a group (ctrl key held down).

**Pull request merged**
